"""
============================================
How to use 7-base_geometry.py
============================================

This module defines a BaseGeometry class.

Usage
=====

Importing the class from the module:
    >>> BaseGeometry = __import__('7-base_geometry').BaseGeometry

Creating an instance of BaseGeometry:
    >>> bg = BaseGeometry()

Testing the area method:
    >>> bg.area()
    Traceback (most recent call last):
    Exception: area() is not implemented

Testing integer_validator with valid input:
    >>> bg.integer_validator("my_int", 12)

    >>> bg.integer_validator("width", 89)

Testing integer_validator with non-integer input:
    >>> bg.integer_validator("name", "John")
    Traceback (most recent call last):
    TypeError: name must be an integer

Testing integer_validator with zero input:
    >>> bg.integer_validator("age", 0)
    Traceback (most recent call last):
    ValueError: age must be greater than 0

Testing integer_validator with negative input:
    >>> bg.integer_validator("distance", -4)
    Traceback (most recent call last):
    ValueError: distance must be greater than 0

Testing integer_validator with float input:
    >>> bg.integer_validator("average", 7.8)
    Traceback (most recent call last):
    TypeError: average must be an integer

Testing integer_validator with bool input:
    >>> bg.integer_validator("valid", True)
    Traceback (most recent call last):
    TypeError: valid must be an integer

Testing integer_validator with None input:
    >>> bg.integer_validator("age", None)
    Traceback (most recent call last):
    TypeError: age must be an integer

Testing integer_validator with no arguments:
    >>> bg.integer_validator()
    Traceback (most recent call last):
    TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

Testing integer_validator with one argument:
    >>> bg.integer_validator("age")
    Traceback (most recent call last):
    TypeError: integer_validator() missing 1 required positional argument: 'value'

Testing integer_validator with three arguments:
    >>> bg.integer_validator("age", 1, 2)
    Traceback (most recent call last):
    TypeError: integer_validator() takes 3 positional arguments but 4 were given
"""